### ISSUE TITLE
\brief docs.

### ISSUE THREAD

**Issue by bakercp** [HalfdanJ/ofDocumentationGenerator#1]
![ofdoc_-](https://cloud.githubusercontent.com/assets/300484/13398638/d6c0d44a-dec4-11e5-9eb3-273ba7834d84.png)

Seems would be useful to have a little more information here if all will be collapsed.

**Comment by HalfdanJ** [comment]
Take a look. I understand your idea, and it does add something great to the site. But it might also be harder to get an overview.. 

You can hide it with `$('.brief').hide()` in developer console
